baseURL = "http://amandasjostrom.github.io/knit-blog"
languageCode = "en-us"
title = "Stickerier"
theme = ["hugo-video", "ananke"]
featured_image = "/images/pexels-photo-267074.jpeg"

# since github pages only supports using root or /docs as source
publishDir = "docs"

[params]
  post_content_classes = "avenir bg-near-white"
  custom_css = ["css/custom.css"]
